import logging
import json
import time
from datetime import datetime, timezone
from typing import Optional


class JSONFormatter(logging.Formatter):
    """
    Format log records as JSON.

    This makes logs easier to search and analyze in tools such as:
    - ELK Stack
    - Datadog
    - CloudWatch
    - Google Cloud Logging
    """

    def format(self, record: logging.LogRecord) -> str:
        log_obj = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "message": record.getMessage(),
            "logger": record.name,
            "module": record.module,
            "function": record.funcName,
        }

        # Add extra structured fields if provided
        # Example:
        # logger.info("Request completed", extra={"extra_data": {"latency_ms": 123}})
        if hasattr(record, "extra_data"):
            log_obj.update(record.extra_data)

        return json.dumps(log_obj)


def get_logger(name: str = "production-api") -> logging.Logger:
    """
    Create and return a structured JSON logger.

    The logger writes JSON logs to stdout/stderr through StreamHandler.
    This is suitable for Docker, FastAPI, cloud logs, and simple production setups.
    """

    logger = logging.getLogger(name)

    # Prevent adding multiple handlers when get_logger() is called many times
    if not logger.handlers:
        handler = logging.StreamHandler()
        handler.setFormatter(JSONFormatter())

        logger.addHandler(handler)
        logger.setLevel(logging.INFO)

        # Prevent duplicate logs from propagating to the root logger
        logger.propagate = False

    return logger


class MetricsCollector:
    """
    Lightweight in-memory metrics collector.

    This is useful for learning, local development, and simple monitoring.

    In real production, replace this with Prometheus:

        from prometheus_client import Counter, Histogram

    Example metrics tracked:
    - Total requests
    - Total errors
    - Error rate
    - Average latency
    - Token usage
    - Cache hit rate

    Note:
    Because this is in-memory, metrics reset when the app restarts.
    """

    def __init__(self):
        self._requests_total = 0
        self._errors_total = 0

        self._latency_sum = 0.0
        self._latency_count = 0

        self._tokens_input = 0
        self._tokens_output = 0

        self._cache_hits = 0
        self._cache_misses = 0

    def record_request(
        self,
        latency_ms: float,
        input_tokens: int = 0,
        output_tokens: int = 0,
        error: bool = False,
        cache_hit: Optional[bool] = None,
    ) -> None:
        """
        Record metrics for a single API request.

        Args:
            latency_ms:
                Total request duration in milliseconds.

            input_tokens:
                Number of input/prompt tokens used by the LLM.

            output_tokens:
                Number of output/completion tokens generated by the LLM.

            error:
                Whether the request failed.

            cache_hit:
                True if response came from cache.
                False if cache was checked but missed.
                None if cache was not used or not checked.
        """

        self._requests_total += 1
        self._latency_sum += latency_ms
        self._latency_count += 1

        self._tokens_input += input_tokens
        self._tokens_output += output_tokens

        if error:
            self._errors_total += 1

        # Only update cache metrics when cache was actually checked
        if cache_hit is True:
            self._cache_hits += 1
        elif cache_hit is False:
            self._cache_misses += 1

    @property
    def summary(self) -> dict:
        """
        Return aggregated metrics as a dictionary.
        """

        avg_latency = (
            self._latency_sum / self._latency_count
            if self._latency_count > 0
            else 0.0
        )

        error_rate = (
            self._errors_total / self._requests_total
            if self._requests_total > 0
            else 0.0
        )

        cache_total = self._cache_hits + self._cache_misses

        cache_hit_rate = (
            self._cache_hits / cache_total
            if cache_total > 0
            else 0.0
        )

        return {
            "total_requests": self._requests_total,
            "total_errors": self._errors_total,
            "error_rate": f"{error_rate:.2%}",
            "avg_latency_ms": round(avg_latency, 2),
            "cache_hits": self._cache_hits,
            "cache_misses": self._cache_misses,
            "cache_hit_rate": f"{cache_hit_rate:.2%}",
            "total_input_tokens": self._tokens_input,
            "total_output_tokens": self._tokens_output,
            "total_tokens": self._tokens_input + self._tokens_output,
        }


class RequestTimer:
    """
    Context manager for timing a request or function block.

    Example:
        with RequestTimer() as timer:
            result = rag_chain.invoke(query)

        print(timer.elapsed_ms)
    """

    def __enter__(self):
        # perf_counter is better than time.time() for measuring durations
        self.start = time.perf_counter()
        self.elapsed_ms = 0.0
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.elapsed_ms = (time.perf_counter() - self.start) * 1000